server:
  port: 80
  compression:
    enabled: true
    mime-types:
      - application/json

spring:
  application:
    name: auth-user
  jpa:
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  liquibase:
    change-log: classpath:/db/changelog.xml






