spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  liquibase:
    change-log: classpath:/db/changelog.xml
  server:
    port: ${port:8080}
  application:
    name: auth-user

api:
  security:
    token:
      secret: ${TOKEN_SECRET:018f015d-6d99-72e3-b3cd-b205d97737b7}
    refresh:
      token:
        secret: ${TOKEN_REFRESH_SECRET:018f015d-9856-767e-a221-d45550f3e1c5}

auth-user:
  datasource:
    jdbcUrl: jdbc:mysql://${DB_HOST}:3306/auth_user?allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    maximumPoolSize: 3
    minimumPoolSize: 3
    connectionTestQuery: SELECT 1
    poolName: security-pool
    driverClassName: com.mysql.cj.jdbc.Driver




