name: quality

on:
  workflow_call:
    pull_request:
      branches:
      - master

jobs:
  pipeline-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build Project and Test
        run: mvn clean test

     # - name: test
     #   run: org.jacoco:jacoco-maven-plugin:prepare-agent test -Dspring.profiles.active=test -Djava.util.PropertyResourceBundle.encoding=UTF=8 -Duser.timezone=UTC



